### ISSUE TITLE
重新命名組織名稱？

### ISSUE THREAD

**Issue by rschiang** [ntu-student-congress/tortue#14]
（雖然跟法規彙編好像沒什麼關係，但這裡似乎比較適合討論XD）

現行的 organization 名稱是 ntu-student-congress（因為 NTUSC 被用掉了），但 Facebook 短網址是用 NTUStudentCouncil。感覺可以跟 FB 統一一下 ~~或是請 NTUSC 改名~~。(・ω・)ノ

**Comment by shouko** [comment]
據了解，本會登記之正式英文名稱為 Student Congress
https://host.cc.ntu.edu.tw/activities/clubInfo.aspx?Club_ID=329&From=clubInfoQuery.aspx
Facebook 粉絲專頁網址使用 council 為誤譯 XDDDD

**Comment by shouko** [comment]
@artistic709 What do you think

**Comment by artistic709** [comment]
好啊，來改個

**Comment by shouko** [comment]
我是說改粉專的
